import tkinter as tk
def oo(ko):ko.config(text='o')
window=tk.Tk()
window.title('tictoctoe')
window.geometry('264x282')
window.update_idletasks()
window_width = window.winfo_width()
window_height = window.winfo_height()
screen_width = window.winfo_screenwidth()
screen_height = window.winfo_screenheight()
x_position = (screen_width - window_width) // 2
y_position = (screen_height - window_height) // 2
window.geometry(f"{window_width}x{window_height}+{x_position}+{y_position}")
lab1=tk.Label(window,cursor='hand2',borderwidth=1,relief='solid',width=12,height=6)
lab1.grid(row=0,column=0)
lab1.bind('<Button-1>',lambda event:oo(lab1))
lab2=tk.Label(window,cursor='hand2',borderwidth=1,relief='solid',width=12,height=6)
lab2.grid(row=0,column=1)
lab2.bind('<Button-1>',lambda event:oo(lab2))
lab3=tk.Label(window,cursor='hand2',borderwidth=1,relief='solid',width=12,height=6)
lab3.grid(row=0,column=2)
lab3.bind('<Button-1>',lambda event:oo(lab3))
lab4=tk.Label(window,cursor='hand2',borderwidth=1,relief='solid',width=12,height=6)
lab4.grid(row=1,column=0)
lab4.bind('<Button-1>',lambda event:oo(lab4))
lab5=tk.Label(window,cursor='hand2',borderwidth=1,relief='solid',width=12,height=6)
lab5.grid(row=1,column=1)
lab5.bind('<Button-1>',lambda event:oo(lab5))
lab6=tk.Label(window,cursor='hand2',borderwidth=1,relief='solid',width=12,height=6)
lab6.grid(row=1,column=2)
lab6.bind('<Button-1>',lambda event:oo(lab6))
lab7=tk.Label(window,cursor='hand2',borderwidth=1,relief='solid',width=12,height=6)
lab7.grid(row=2,column=0)
lab7.bind('<Button-1>',lambda event:oo(lab7))
lab8=tk.Label(window,cursor='hand2',borderwidth=1,relief='solid',width=12,height=6)
lab8.grid(row=2,column=1)
lab8.bind('<Button-1>',lambda event:oo(lab8))
lab9=tk.Label(window,cursor='hand2',borderwidth=1,relief='solid',width=12,height=6)
lab9.grid(row=2,column=2)
lab9.bind('<Button-1>',lambda event:oo(lab9))
window.mainloop()